### PR TITLE
🎉 Add advanced setting to allow all website access permission.

### LINKED ISSUE #168: Add a setting to allow extension's access to all websites in Chrome.
## This issue is a 

- [x] feature

Add a setting to enable Tusk's access to edit all website's data without prompt in chrome. 

Might be hidden or something, only for advanced users, but when you want to be really productive. The prompts about access to data in specific domain become annoying. Open for discussion, especially since it has serious security implications.

### PR DESCRIPTION
**Pull request by zmilonas**
Closes #168 

Tested with Chrome 69 on macOS

Demo screen recording here: https://gfycat.com/ForthrightDefensiveIberianemeraldlizard

### CODE REVIEW

**Comment by zmilonas** [comment]
@subdavis thanks for the feedback 

ad 1. Good to know for the future :D 
ad 2. I must've been to careless when implementing and didn't know i can programatically remove the permission as well. I changed it up

**Comment by subdavis** [comment]
@zmilonas looks like there are some conflicts here.  Once those get sorted out, we can merge.

**Comment by zmilonas** [comment]
@subdavis conflicts resolved :)

**Comment by subdavis** [comment]
Opened #199 to tackle some of the anomalies in options page styles.  Otherwise, LGTM.

**Comment by subdavis** [comment]
I don't know if I'm losing my mind, but this broke.


```
options.html:1 Unchecked runtime.lastError while running permissions.request: This function must be called during a user gesture
    at allOriginPermission (chrome-extension://fmhmiaejopepamlcjkncpgpdjichnecm/build/options.build.js:6602:24)
    at Ni.run (chrome-extension://fmhmiaejopepamlcjkncpgpdjichnecm/dll/dll.library.js:100:6484)
    at zt (chrome-extension://fmhmiaejopepamlcjkncpgpdjichnecm/dll/dll.library.js:95:74289)
    at Array.<anonymous> (chrome-extension://fmhmiaejopepamlcjkncpgpdjichnecm/dll/dll.library.js:95:68397)
    at MessagePort.at (chrome-extension://fmhmiaejopepamlcjkncpgpdjichnecm/dll/dll.library.js:95:68226)
```

I remember testing this PR and it working.  I'm on `Chromium 67.0.3396.99 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)`

This is now the same thing that Firefox does as mentioned in the README.  Can you reproduce, @zmilonas?  I'm running on commit 95ffcd96dd8ba1b11c1af307a59cedbdcb46fccc

**Comment by zmilonas** [comment]
@ubdavis 
Can't reproduce :/. What are the steps?

**Comment by subdavis** [comment]
Just try to toggle on this feature from advanced settings.  What version of Chrome are you on, and what platform?

**Pull request merged**
