### PR TITLE
Add pCloud backup

### PR DESCRIPTION
**Pull request by labsin**
Get the database from pCloud.
Haven't tested with Chrome.
The client_id is now from my account. See commit message of commit 76bb9c0 for details.

### CODE REVIEW

**Comment by subdavis** [comment]
Hey there!  Thanks for submitting a PR for this!  Sorry I haven't had a chance to look at it yet.  I promise I'll get feedback sometime today.

:D

**Comment by subdavis** [comment]
I've created a new branch of Tusk called `pcloud`

Please open your pull request against this branch.  There are a few things missing, like the SVG icon.  I'm also going to switch over the client_id to an application I own and enable google chrome support.

Overall very happy with this.  Thanks for taking the time to put this together.  Also thank you for following the OAuth pattern perfectly.  

What did you think of the code organization, development process, etc?  What could be done better.

**Comment by labsin** [comment]
I opened a new pull requets so I'll close this one

https://github.com/subdavis/Tusk/pull/141

**Comment by labsin** [comment]
For the organization. Hosted on Github with the issue tracker and pull requests is straight forward.

I haven't used yarn etc before so I had to search a bit. Building was a bit slow. I've added the following build script for testing:
"build-dev": "cross-env webpack --progress --hide-modules"

**Comment by subdavis** [comment]
Agree that speed was an issue,

Just merged another branch to speed things up, bringing rebuid time down to 2.5ish seconds :)

Thanks again for your work.  I'll get this into the webstore later this week.

**Pull request closed without merging**
