### PR TITLE
Include the new logo in README

### PR DESCRIPTION
**Pull request by ggabogarcia**
I hope you like it

### CODE REVIEW

**Comment by zmilonas** [comment]
I would actually recommend adding the logo to the repo to the assets folder or dropping the file in the text editor on github to upload it to github's cdn so that we're not reliant on external services to render it on GitHub. Also maybe let's use markdown instead of HTML

**Comment by ggabogarcia** [comment]
Hello, the files were sent by mail. Everything is on the g-drive :)

**Comment by subdavis** [comment]
I'll take care of adding this.  I want to add to readme, app, and website all at once.  Thank you

**Comment by subdavis** [comment]
BTW @ggabogarcia this has been done!

**Pull request closed without merging**
